### ISSUE TITLE
Docs in the README

### ISSUE THREAD

**Issue by mcollina** [smartiniOnGitHub/cloudevent.js#1]
Can you add some docs in the README? It's not really clear how to use this.

**Comment by smartiniOnGitHub** [comment]
Hi, yes sure I'll add ASAP; the problem is that current features (that I need to better describe in a CHANGELOG) are to create CloudEvent instances and check/validate them (there are some examples in unit tests but I agree that I need to improve).
Next feature is serialize in JSON (I'm still thinking at a good way to do it, because the data part could be encoded at the same time in different formats), so I'll add more info ASAP.
Thanks for now,
Sandro

**Comment by smartiniOnGitHub** [comment]
@mcollina Hi Matteo, I should be able to publish first release in a few days now ... do you think updated example (in the README and now even in a Node.js script in a dedicated 'example' folder) could be good enough to describe simple usage of this library ?
Maybe I could remove some assertions from the README, what do you think ?
I just added even a link to published API documentation (it will be updated soon too).

**Comment by smartiniOnGitHub** [comment]
Ok, I'll do more cleanup ... but on the more API docs currently there isn't so much exposed by CloudEvent class so can't show more, but of course if you have some idea tell me, I'll be happy to improve it :-) .
On the option argument I tried to use that new ES6 syntax to simplify management of argument default values (to have all the implementation compliant to latest ES features in any place, but still compatible with Node.js 8.11.x), does it make sense ?

**Comment by smartiniOnGitHub** [comment]
More info/cleanup in the README (and no more exclude the 'example' folder in the npm package), and first release (0.1.0) just published, I hope things are a little more clear now.
Be free to reopen if/when needed. 
Thanks for now, Sandro
